NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.vc1.dao-vc.ir-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.vc1.dao-vc.ir-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca.vc1.dao-vc.ir-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca.vc1.dao-vc.ir-cert.pem
    OrganizationalUnitIdentifier: orderer
