OrdererOrgs:
  - Name: DAOOrdererOrg
    Domain: dao-vc.ir
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3

PeerOrgs:
  - Name: OrgVC1
    Domain: vc1.dao-vc.ir
    Template:
      Count: 3  # تعداد نودهای Peer برای این سازمان
    Users:
      Count: 1  # تعداد کاربران Client برای این سازمان

  - Name: OrgVC2
    Domain: vc2.dao-vc.ir
    Template:
      Count: 3
    Users:
      Count: 1

  - Name: OrgDAO
    Domain: dao.dao-vc.ir
    Template:
      Count: 1  # یک نود برای مدیریت DAO
    Users:
      Count: 2  # حداقل دو کاربر برای مدیریت DAO
