OrdererOrgs:
  - Name: DAOOrdererOrg
    Domain: dao-vc.ir
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3

PeerOrgs:
  - Name: OrgVC1
    Domain: vc1.dao-vc.ir
    Template:
      Count: 3
    Users:
      Count: 1

  - Name: OrgVC2
    Domain: vc2.dao-vc.ir
    Template:
      Count: 3
    Users:
      Count: 1

  - Name: OrgDAO
    Domain: dao.dao-vc.ir
    Template:
      Count: 1
    Users:
      Count: 2
