General:
  ListenAddress: 0.0.0.0  # برای دسترسی به همه آدرس‌های شبکه
  ListenPort: 7150  # تنظیم پورت مطابق تنظیمات اصلی
  TLS:
    Enabled: true
    PrivateKey: /etc/hyperledger/fabric/crypto/ordererOrganizations/dao-vc.ir/orderers/orderer1.dao-vc.ir/tls/server.key
    Certificate: /etc/hyperledger/fabric/crypto/ordererOrganizations/dao-vc.ir/orderers/orderer1.dao-vc.ir/tls/server.crt
    RootCAs:
      - /etc/hyperledger/fabric/crypto/ordererOrganizations/dao-vc.ir/orderers/orderer1.dao-vc.ir/tls/ca.crt
  LocalMSPDir: /etc/hyperledger/fabric/msp
  LocalMSPID: OrdererMSP
  BootstrapMethod: file
  BootstrapFile: /etc/hyperledger/fabric/genesisblock

FileLedger:
  Location: /var/hyperledger/production/orderer
  Prefix: file

Operations:
  ListenAddress: 127.0.0.1:8444 # تنظیم پورت آزاد برای عملیات

Metrics:
  Provider: prometheus
  Statsd:
    Network: udp
    Address: 127.0.0.1:8125
    WriteInterval: 10s
    Prefix: fabric

Kafka:
  Retry:
    ShortInterval: 5s
    ShortTotal: 10m
    LongInterval: 5m
    LongTotal: 12h
  TLS:
    Enabled: false

Debug:
  BroadcastTraceDir: /var/hyperledger/production/orderer/broadcast
  DeliverTraceDir: /var/hyperledger/production/orderer/deliver

Consensus:
  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
  WALDir: /var/hyperledger/production/orderer/etcdraft/wal

ChannelParticipation:
  Enabled: true
  MaxRequestBodySize: 1048576

Admin:
  ListenAddress: 127.0.0.1:9443
  TLS:
    Enabled: false